// Generated by github.com/greatwing/tabtoy
// DO NOT EDIT!!
// Version: 
export namespace sensitive_tab {
	// export var Data:Table = null;

	// export function InitData(json: Object|string) {
	// 	Data = Table.FromJSON(json);
	// }

	var Data:Table = null;    export function getData():Table { return Data; }

	export function InitData(json: Object|string) {
		Data = Table.FromJSON(json);
	}

	

	
	export class SensitiveWordsTable { 
		SensitiveWords : string // 屏蔽字 
	}
	

	// Combine struct
	export class Table { 
		SensitiveWordsTable : SensitiveWordsTable[] // table: SensitiveWordsTable 

		// Indices 

		

		//根据json创建Table
		static FromJSON(json: Object|string): Table {
			let result: Table;
            if (typeof json === 'string') {
                // if it's a string, parse it first
                result= JSON.parse(json, Table.reviver);
            } else {
                // create an instance of the Table class
                let tbl = new Table()
                // copy all the fields from the json object
                result = Object.assign(tbl, json);
            }
			result.BuildData();
			return result;
		}

        static reviver(key: string, value: any): any {
            return key === "" ? Table.FromJSON(value) : value;
        }

		// 清除索引和数据
		ResetData() {
			
			this.SensitiveWordsTable = [] 
			
		}

		// 构建索引
		BuildData() {
			
		}
	}
}
